# name: deploy

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           node-version: '18.4.0'
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '18.4.0'
#       - run: yarn install
#       - run: yarn run build:h5
#       - uses: actions/upload-artifact@v3
#         with:
#           path: ./dist/build/h5

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     if: github.ref=='refs/heads/master'
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           node-version: 'v16.13.0'
#           path: ./dist/build/h5
#       - uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./dist/build/h5/artifact

#   gitee:
#     needs: deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: Sync To Gitee
#         uses: wearerequired/git-mirror-action@master
#         env:
#           # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
#           SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
#         with:
#           # 注意替换为你的 GitHub 源仓库地址
#           source-repo: git@github.com:erabbit-dev/erabbit-uni-app.git
#           # 注意替换为你的 Gitee 目标仓库地址
#           destination-repo: git@gitee.com:Megasu/uniapp-shop-vue3-ts.git
#           # dry-run: true

#       - name: Build Gitee Pages
#         uses: yanglbme/gitee-pages-action@main
#         with:
#           # 注意替换为你的 Gitee 用户名
#           gitee-username: megasu@qq.com
#           # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
#           gitee-password: ${{ secrets.GITEE_PASSWORD }}
#           # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
#           gitee-repo: Megasu/uniapp-shop-vue3-ts
#           # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
#           branch: gh-pages
#           # directory: docs/.vitepress/dist
